ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"
  skip: [ty]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.22
    hooks:
      # Run the linter.
      - id: ruff-check
        args: ["--fix", "--show-fixes"]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/astral-sh/ty-pre-commit
    # ty version.
    rev: v0.0.61
    hooks:
      - id: ty

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: "v0.11.0.1"
    hooks:
      - id: shellcheck

  - repo: https://github.com/adamchainz/blacken-docs
    rev: "1.20.0"
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==22.12.0

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.3
    hooks:
      - id: codespell
        exclude: ^(LICENSE$)

  - repo: https://github.com/henryiii/validate-pyproject-schema-store
    rev: 2026.07.20
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.37.4
    hooks:
      - id: check-readthedocs
      - id: check-github-workflows
